export const AllProducts = {
  state: {
    items: [
      {
        id: 1,
        name: "Iphone 13 pro",
        corpus: "Металл стекло",
        color: "Ocean Blue",
        tips: "IPS",
        battery: "lition",
        size: "5.2",
        img: "/src/assets/img/catalog/phones/ip13.png",
        price: "550000тг",
        option: ["Корпус", "Размер", "Цвет", "Батарея", "Экран"],
      },
      {
        id: 2,
        name: "Iphone 11 pro",
        corpus: "Металл стекло",
        color: "Grey",
        tips: "IPS",
        battery: "lition",
        size: "4.9",
        img: "/src/assets/img/catalog/phones/ip11.png",
        price: "300000тг",
        option: ["Корпус", "Размер", "Цвет", "Батарея", "Экран"],
      },
      {
        id: 3,
        name: "Iphone 12 pro",
        corpus: "Металл стекло",
        color: "Grey",
        tips: "IPS",
        battery: "lition",
        size: "5.1",
        img: "/src/assets/img/catalog/phones/ip12.png",
        price: "360000тг",
        option: ["Корпус", "Размер", "Цвет", "Батарея", "Экран"],
      },

      {
        id: 4,
        name: "Iphone X",
        corpus: "Металл стекло",
        color: "Белый",
        tips: "IPS",
        battery: "lition",
        size: "4.7",
        img: "/src/assets/img/catalog/phones/ipx.png",
        price: "220000тг",
        option: ["Корпус", "Размер", "Цвет", "Батарея", "Экран"],
      },
      {
        id: 5,
        name: "Iphone 14 pro",
        corpus: "Металл стекло",
        color: "Белый",
        tips: "IPS",
        battery: "lition",
        size: "5.2",
        img: "/src/assets/img/catalog/phones/ip14.png",
        price: "650000тг",
        option: ["Корпус", "Размер", "Цвет", "Батарея", "Экран"],
      },

      {
        id: 6,
        name: "DJI Mavic Pro",
        corpus: "Пластик",
        color: "Черный",
        tips: "743",
        battery: "25мин",
        size: "Full hd / 60fps",
        img: "/src/assets/img/catalog/drones/mv1.png",
        price: "350000тг",
        option: ["Корпус", "Камера", "Цвет", "Время полета", "Вес"],
      },
      {
        id: 7,
        name: "DJI Mavic Pro 2",
        corpus: "Пластик",
        color: "Серый",
        tips: "740",
        battery: "30мин",
        size: "4k / 60fps",
        img: "/src/assets/img/catalog/drones/mv2.png",
        price: "540000тг",
        option: ["Корпус", "Камера", "Цвет", "Время полета", "Вес"],
      },
      {
        id: 8,
        name: "DJI Mavic Pro 3",
        corpus: "Пластик",
        color: "Черный",
        tips: "690",
        battery: "35мин",
        size: "4k / 120fps",
        img: "/src/assets/img/catalog/drones/mv3.png",
        price: "820000тг",
        option: ["Корпус", "Камера", "Цвет", "Время полета", "Вес"],
      },
      {
        id: 9,
        name: "DJI Mavic Air",
        corpus: "Пластик",
        color: "Белый",
        tips: "620",
        battery: "30мин",
        size: "2k / 60fps",
        img: "/src/assets/img/catalog/drones/mvair.png",
        price: "310000тг",
        option: ["Корпус", "Камера", "Цвет", "Время полета", "Вес"],
      },

      {
        id: 10,
        name: "Ipad air 2022",
        corpus: "Метал/Стекло",
        color: "Серый",
        tips: "IPS",
        battery: "M1",
        size: "256gb",
        img: "/src/assets/img/catalog/ipads/ipadair2022.png",
        price: "370000тг",
        option: ["Корпус", "Памят", "Цвет", "Процессор", "Экран"],
      },
      {
        id: 11,
        name: "Ipad pro 2022",
        corpus: "Метал/Стекло",
        color: "Серый/Белый",
        tips: "XDR",
        battery: "M1",
        size: "256gb",
        img: "/src/assets/img/catalog/ipads/ipadpro2022.png",
        price: "720000тг",
        option: ["Корпус", "Памят", "Цвет", "Процессор", "Экран"],
      },
      {
        id: 12,
        name: "Ipad pro 2020",
        corpus: "Метал/Стекло",
        color: "Blue Space",
        tips: "IPS",
        battery: "A12 Bionic",
        size: "128gb",
        img: "/src/assets/img/catalog/ipads/ipadpro2020.png",
        price: "420000тг",
        option: ["Корпус", "Памят", "Цвет", "Процессор", "Экран"],
      },

      {
        id: 13,
        name: "Apple Watch Series 5",
        corpus: "Метал/Стекло",
        color: "Blue Space",
        tips: "OLED LTPO",
        battery: "180 мАч",
        size: "40 мм",
        img: "/src/assets/img/catalog/watches/wh5.png",
        price: "220000тг",
        option: ["Корпус", "Размер", "Цвет", "Емкость", "Экран"],
      },
      {
        id: 14,
        name: "Apple Watch Series 7",
        corpus: "Золото/Розовый",
        color: "Розовый",
        tips: "OLED LTPO",
        battery: "200 мАч",
        size: "41 мм",
        img: "/src/assets/img/catalog/watches/wh7.png",
        price: "250000тг",
        option: ["Корпус", "Размер", "Цвет", "Емкость", "Экран"],
      },
      {
        id: 15,
        name: "Apple Watch Series 8",
        corpus: "Металл/Бежевый",
        color: "Серый",
        tips: "OLED Retina",
        battery: "284 мАч",
        size: "41 мм",
        img: "/src/assets/img/catalog/watches/wh8.png",
        price: "300000тг",
        option: ["Корпус", "Размер", "Цвет", "Емкость", "Экран"],
      },
      {
        id: 16,
        name: "Apple Watch Series ULTRA",
        corpus: "Метал/Стекло",
        color: "Серый/Белый",
        tips: "OLED Retina",
        battery: "542 мАч",
        size: "49 мм",
        img: "/src/assets/img/catalog/watches/whultra.png",
        price: "490000тг",
        option: ["Корпус", "Размер", "Цвет", "Емкость", "Экран"],
      },
    ],
  },
  getters: {
    items: state => state.items,
  }
};
